module.exports = {
    "Spass": 0,
    "Void Tetra": 0,
    "Hoptune Goby": 0,
    "Pulsar Danio": 0,
    "Carpo Carp": 0,
    "Dwarf Star Loach": 0,
    "Space Humuhumunukunukuāpuaʻa": 0,
    "Quasarracuda": 0,
    "Galaxy Frog": 0,
    "Big Gulper": 0,
    "Gamma Rays": 0,
    "Sun Rays": 0,
    "Moon Rays": 0,
    "Diashian Rays": 0,
    "Vesta Crab": 0,
    "Corot Lobster": 0,
    "Starfish": 0,
    "Clusterfish": 0,
    "Magnetar Beetle": 0,
    "Nebula Hive": 0,
    "Onyx System Weaver": 0,
    "Bulkheads": 0,
    "Astrofin": 0,
}